### ISSUE TITLE
Update opshin dependency

### ISSUE THREAD

**Issue by juliusfrost** [OpShin/opshin-starter-kit#1]
I followed the instructions to run on demeter and got this error:

```
Traceback (most recent call last):
  File "/config/workspace/repo/src/off_chain/collect_vest.py", line 98, in <module>
    main()
  File "/config/.cache/pypoetry/virtualenvs/opshin-starter-kit-d63vU2Dj-py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/config/.cache/pypoetry/virtualenvs/opshin-starter-kit-d63vU2Dj-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/config/.cache/pypoetry/virtualenvs/opshin-starter-kit-d63vU2Dj-py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/config/.cache/pypoetry/virtualenvs/opshin-starter-kit-d63vU2Dj-py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/config/workspace/repo/src/off_chain/collect_vest.py", line 68, in main
    redeemer = Redeemer(0)
TypeError: Redeemer.__init__() missing 1 required positional argument: 'data'
```

It seems the new pycardano version caused this so we would need to set `opshin = "^0.12.0"` in https://github.com/OpShin/opshin-starter-kit/blob/5dd2470e11457a6db35e938453880908e0eb13b2/pyproject.toml#L12 and do `poetry update` to update `poetry.lock`.

**Comment by nielstron** [comment]
Thanks for checking!
